using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMove : MonoBehaviour
{
    public float runSpeed = 7;
    public float rotationSpeed = 250;

    public Animator animator;

    private float x, y;

    public Rigidbody rb;
    public float jumpHeight = 3;

    public Transform groundCheck;
    public float groundDistance = 0.1f;
    public LayerMask groundMask;

    bool isGrounded;
    
    void Update()
    {
        x = Input.GetAxis("Horizontal");

        y = Input.GetAxis("Vertical");

        transform.Rotate(0, x * Time.deltaTime *rotationSpeed, 0);

        transform.Translate(0, 0, y * Time.deltaTime*runSpeed);

        animator.SetFloat("velX", x);
        animator.SetFloat("velY", y);

        isGrounded = Physics.CheckSphere(groundCheck.position, groundDistance, groundMask);

        if (Input.GetKey("space") && isGrounded)
        {
            animator.Play("Jumping");

            Invoke("Jumping", 1f);
        }
    }

    public void Jumping()
    {
        rb.AddForce(Vector3.up*jumpHeight,ForceMode.Impulse);
    }

}
